services:
  chatwoot-automation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    command: ["./entrypoint.sh"]
    networks:
      - chatwoot-network

networks:
  chatwoot-network:
    driver: bridge