name: CI Tests

on:
  push:
    branches: [ main, develop, 'release/*', 'hotfix/*' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        TEST_DEEPSEEK_API_KEY: ${{ secrets.TEST_DEEPSEEK_API_KEY }}
        TEST_CHATWOOT_API_TOKEN: ${{ secrets.TEST_CHATWOOT_API_TOKEN }}
        TEST_LANGCHAIN_API_KEY: ${{ secrets.TEST_LANGCHAIN_API_KEY }}
        TEST_CHATWOOT_WEBHOOK_SECRET: ${{ secrets.TEST_CHATWOOT_WEBHOOK_SECRET }}
      run: |
        pytest tests/ -v --cov=chatwoot_langgraph --cov-report=xml
    
    - name: Upload coverage to Codecov
      if: github.event_name != 'pull_request'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ github.ref }}
